[build]
  command = ""
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/generate"
  to = "/.netlify/functions/generate-prompts"
  status = 200
